name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  release:
    name: Build and Release
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish for Windows x64
      run: dotnet publish ReplaceText/ReplaceText.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win-x64

    - name: Publish for Windows x86
      run: dotnet publish ReplaceText/ReplaceText.csproj -c Release -r win-x86 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win-x86

    - name: Publish for Linux x64
      run: dotnet publish ReplaceText/ReplaceText.csproj -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/linux-x64

    - name: Publish for macOS x64
      run: dotnet publish ReplaceText/ReplaceText.csproj -c Release -r osx-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/osx-x64

    - name: Publish for macOS ARM64
      run: dotnet publish ReplaceText/ReplaceText.csproj -c Release -r osx-arm64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/osx-arm64

    - name: Create ZIP archives
      run: |
        Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./ReplaceText-win-x64.zip
        Compress-Archive -Path ./publish/win-x86/* -DestinationPath ./ReplaceText-win-x86.zip
        Compress-Archive -Path ./publish/linux-x64/* -DestinationPath ./ReplaceText-linux-x64.zip
        Compress-Archive -Path ./publish/osx-x64/* -DestinationPath ./ReplaceText-osx-x64.zip
        Compress-Archive -Path ./publish/osx-arm64/* -DestinationPath ./ReplaceText-osx-arm64.zip

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          ReplaceText-win-x64.zip
          ReplaceText-win-x86.zip
          ReplaceText-linux-x64.zip
          ReplaceText-osx-x64.zip
          ReplaceText-osx-arm64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ReplaceText-Release
        path: |
          ReplaceText-win-x64.zip
          ReplaceText-win-x86.zip
          ReplaceText-linux-x64.zip
          ReplaceText-osx-x64.zip
          ReplaceText-osx-arm64.zip
        retention-days: 90
